#!/bin/sh

set -e

case "$1" in
		purge)
				# rm /etc/btblocklist/config.json
                rmdir --ignore-fail-on-non-empty /etc/btblocklist
				test -f /var/lib/btblocklist/cache.gob.gz && rm /var/lib/btblocklist/cache.gob.gz
                rmdir --ignore-fail-on-non-empty /var/lib/btblocklist
                userdel "btblocklist"
                # groupdel "btblocklist"
				;;
esac

#DEBHELPER#

exit 0
