#!/bin/sh

set -e

case "$1" in
		configure)
				adduser --system --disabled-password --disabled-login --home /var/empty --no-create-home --quiet --force-badname --group "btblocklist"
				chmod 640 /etc/btblocklist/config.json
				chown root:btblocklist /etc/btblocklist/config.json
				mkdir -p /var/lib/btblocklist
				chown btblocklist: /var/lib/btblocklist
				chmod 750 /var/lib/btblocklist
				;;
esac

#DEBHELPER#

exit 0
